<?php
$fbfanbox = $this->getFbfanbox();
if($fbfanbox['enable'])
{
	$box_content="";
	$box_content .='<iframe src="http://www.facebook.com/plugins/likebox.php?href='. urlencode($fbfanbox['fb_page_url']);
	if($fbfanbox['box_width'])
	{
		$box_content .= '&amp;width='. $fbfanbox['box_width'];
	}
	if($fbfanbox['box_height'])
	{
		$box_content .= '&amp;height='. $fbfanbox['box_height'];
	}
	
	$box_content .= '&amp;colorscheme=light&amp;connections='. $fbfanbox['connection'];
	
	if($fbfanbox['header'])
	{
		$box_content .= '&amp;header=true';
	} else {
		$box_content .= '&amp;header=false';
	}
	
	if($fbfanbox['stream'])
	{
		$box_content .= '&amp;stream=true';
	}
	$box_content .= '" scrolling="no" frameborder="0" allowTransparency="true" style="border:none; overflow:hidden; ';
	
	if($fbfanbox['box_width'])
	{
		$box_content .= ' width:'. $fbfanbox['box_width'] . 'px; ';
	}
	if($fbfanbox['box_height'])
	{
		$box_content .= ' height:'. $fbfanbox['box_height'] . 'px; ';
	}
	$box_content .= '"></iframe>';
	
	echo("<div id='fbfanbox'>");
	echo($box_content);
	echo("<div style='font-size:9px;display:none;'><a href='http://www.magestore.com/magento-extensions.html'>Magento Extensions</a></div>");
    echo("</div>");

}
?>