<?php
//setting parameters
$authcode= $_GET["code"];
$clientid = Mage::helper('invitefriends')->getgmailClientid();
$clientsecret = Mage::helper('invitefriends')->getgmailClientsecretkey();
//$redirecturi='https://www.localhost.com/magento_dev/magento1.6.0/invitefriends/index/gmailinvite';
$redirecturi = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB).'invitefriends/index/gmailinvite';
$fields=array(
    'code'=>  urlencode($authcode),
    'client_id'=>  urlencode($clientid),
    'client_secret'=>  urlencode($clientsecret),
    'redirect_uri'=>  urlencode($redirecturi),
    'grant_type'=>  urlencode('authorization_code')
);
//url-ify the data for the POST
$fields_string='';
foreach($fields as $key=>$value) { $fields_string .= $key.'='.$value.'&'; }
$fields_string=rtrim($fields_string,'&');
//open connection
$ch = curl_init();
//set the url, number of POST vars, POST data
curl_setopt($ch,CURLOPT_URL,'https://accounts.google.com/o/oauth2/token');
curl_setopt($ch,CURLOPT_POST,5);
curl_setopt($ch,CURLOPT_POSTFIELDS,$fields_string);
// Set so curl_exec returns the result instead of outputting it.
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
//to trust any ssl certificates
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
//execute post
$result = curl_exec($ch);
//close connection
curl_close($ch);
//extracting access_token from response string
$response=  json_decode($result);
$accesstoken= $response->access_token;
//passing accesstoken to obtain contact details
$xmlresponse=  file_get_contents('https://www.google.com/m8/feeds/contacts/default/full?oauth_token='.$accesstoken);
//reading xml using SimpleXML
$xml=  new SimpleXMLElement($xmlresponse);
$xml->registerXPathNamespace('gd', 'http://schemas.google.com/g/2005');
$result = $xml->xpath('//gd:email');
?>
<h2><?php echo $this->__('Invite Friends via Gmail');?></h2>
<ul class="gmail_invite">
<?php
foreach ($result as $title) {
  $email = $title->attributes()->address;
  ?>
<li>
<span><?php echo $email;?></span>

                <input type="hidden" name="email" id="email" value="<?php echo $email;?>">
                <button id="firstbtn" name="firstbtn" class="button" onclick="sendinvitation('<?php echo $email;?>');"><span><span id="<?php echo $email;?>"><?php echo $this->__('Send Invite');?></span></span></button>

</li>
<?php
}
?>
</ul>
<script type="text/javascript">
//<![CDATA[
var strRedirectUrl = "<?php echo $_SERVER['REQUEST_URI'];?>";
function sendinvitation(email){
if(email != ''){
    document.getElementById("firstbtn").disabled=true;
    var send_invitation_url = '<?php echo Mage::getBaseUrl(); ?>invitefriends/index/mailinvite?email='+email;
    var xmlhttp;
    if (window.XMLHttpRequest)
      {// code for IE7+, Firefox, Chrome, Opera, Safari
      xmlhttp=new XMLHttpRequest();
      }
    else
      {// code for IE6, IE5
      xmlhttp=new ActiveXObject("Microsoft.XMLHTTP");
      }
    
    xmlhttp.onreadystatechange=function()
      {
      if (xmlhttp.readyState==4 && xmlhttp.status==200)
        {
            alert('Invited Successfully');
            document.getElementById(email).innerHTML = "<?php echo $this->__('Invited Successfully');?>";
            document.getElementById("firstbtn").disabled=true;            
        }
      }
    xmlhttp.open("POST",send_invitation_url,true);
    xmlhttp.send();
}
}
//]]>
</script>