<?php
class Magentothem_Themeoptions_Model_Config_Customfieldfont
{

    public function toOptionArray()
    {
	    return array(
			array('value'=>'','label' => 'Select Font'),
			array('value'=>'Aclonica','label' => 'Aclonica'),
			array('value'=>'Allan','label' => 'Allan'),
			array('value'=>'Anonymous+Pro','label' => 'Anonymous Pro'),
			array('value'=>'Allerta+Stencil','label' => 'Allerta Stencil'),
			array('value'=>'Allerta','label' => 'Allerta'),
			array('value'=>'Amaranth','label' => 'Amaranth'),
			array('value'=>'Anton','label' => 'Anton'),
			array('value'=>'Arimo','label' => 'Arimo'),
			array('value'=>'Artifika','label' => 'Artifika'),
			array('value'=>'Arvo','label' => 'Arvo'),
			array('value'=>'Asset','label' => 'Asset'),
			array('value'=>'Astloch','label' => 'Astloch'),
			array('value'=>'Bangers','label' => 'Bangers'),
			array('value'=>'Bentham','label' => 'Bentham'),
			array('value'=>'Bevan','label' => 'Bevan'),
			array('value'=>'Bigshot+One','label' => 'Bigshot One'),
			array('value'=>'Bowlby+One','label' => 'Bowlby One'),
			array('value'=>'Brawler','label' => 'Brawler '),
			array('value'=>'Buda:300','label' => 'Buda'),
			array('value'=>'Cabin','label' => 'Cabin'),
			array('value'=>'Calligraffitti','label' => 'Calligraffitti'),
			array('value'=>'Candal','label' => 'Candal'),
			array('value'=>'Cantarell','label' => 'Cantarell'),
			array('value'=>'Cardo','label' => 'Cardo'),
			array('value'=>'Carter One','label' => 'Carter One'),
			array('value'=>'Caudex','label' => 'Caudex'),
			array('value'=>'Chewy','label' => 'Chewy'),
			array('value'=>'Coda','label' => 'Coda'),
			array('value'=>'Coming+Soon','label' => 'Coming Soon'),
			array('value'=>'Copse','label' => 'Copse'),
			array('value'=>'Corben:700','label' => 'Corben'),
			array('value'=>'Cousine','label' => 'Cousine'),
			array('value'=>'Crafty+Girls','label' => 'Crafty Girls'),
			array('value'=>'Crimson+Text','label' => 'Crimson Text'),
			array('value'=>'Crushed','label' => 'Crushed'),
			array('value'=>'Cuprum','label' => 'Cuprum'),
			array('value'=>'Damion','label' => 'Damion'),
			array('value'=>'Dancing+Script','label' => 'Dancing Script'),
			array('value'=>'Didact+Gothic','label' => 'Didact Gothic'),
			array('value'=>'Droid+Sans','label' => 'Droid Sans'),
			array('value'=>'Droid+Serif','label' => 'Droid Serif'),
			array('value'=>'EB+Garamond','label' => 'EB Garamond'),
			array('value'=>'Expletus+Sans','label' => 'Expletus Sans'),
			array('value'=>'Forum','label' => 'Forum'),
			array('value'=>'Francois+One','label' => 'Francois One'),
			array('value'=>'Geo','label' => 'Geo'),
			array('value'=>'Goblin+One','label' => 'Goblin One'),
			array('value'=>'Gravitas+One','label' => 'Gravitas One'),
			array('value'=>'Gruppo','label' => 'Gruppo'),
			array('value'=>'Inconsolata','label' => 'Inconsolata'),
			array('value'=>'Indie+Flower','label' => 'Indie Flower'),
			array('value'=>'Irish+Grover','label' => 'Irish Grover'),
			array('value'=>'Irish+Growler','label' => 'Irish Growler'),
			array('value'=>'Istok+Web','label' => 'Istok Web'),
			array('value'=>'Judson','label' => 'Judson'),
			array('value'=>'Jura','label' => ' Jura Regular'),
			array('value'=>'Jura:500','label' => ' Jura 500'),
			array('value'=>'Jura:600','label' => ' Jura 600'),
			array('value'=>'Kameron','label' => 'Kameron'),
			array('value'=>'Kenia','label' => 'Kenia'),
			array('value'=>'Kranky','label' => 'Kranky'),
			array('value'=>'Kreon','label' => 'Kreon'),
			array('value'=>'Kristi','label' => 'Kristi'),
			array('value'=>'Lato:100','label' => 'Lato 100'),
			array('value'=>'Lato','label' => 'Lato'),
			array('value'=>'Lato:900','label' => 'Lato 900'),
			array('value'=>'League+Script','label' => 'League Script'),
			array('value'=>'Lekton','label' => ' Lekton '),
			array('value'=>'Limelight','label' => ' Limelight '),
			array('value'=>'Lobster','label' => 'Lobster'),
			array('value'=>'Lobster Two','label' => 'Lobster Two'),
			array('value'=>'Lora','label' => 'Lora'),
			array('value'=>'Luckiest+Guy','label' => 'Luckiest Guy'),
			array('value'=>'Maiden+Orange','label' => 'Maiden Orange'),
			array('value'=>'Mako','label' => 'Mako'),
			array('value'=>'Maven+Pro','label' => ' Maven Pro'),
			array('value'=>'Maven+Pro:500','label' => ' Maven Pro 500'),
			array('value'=>'Maven+Pro:700','label' => ' Maven Pro 700'),
			array('value'=>'Maven+Pro:900','label' => ' Maven Pro 900'),
			array('value'=>'Meddon','label' => 'Meddon'),
			array('value'=>'MedievalSharp','label' => 'MedievalSharp'),
			array('value'=>'Megrim','label' => 'Megrim'),
			array('value'=>'Merriweather','label' => 'Merriweather'),
			array('value'=>'Metrophobic','label' => 'Metrophobic'),
			array('value'=>'Michroma','label' => 'Michroma'),
			array('value'=>'Miltonian','label' => 'Miltonian'),
			array('value'=>'Modern Antiqua','label' => 'Modern Antiqua'),
			array('value'=>'Monofett','label' => 'Monofett'),
			array('value'=>'Molengo','label' => 'Molengo'),
			array('value'=>'Muli:300','label' => 'Muli Light'),
			array('value'=>'Muli','label' => 'Muli Regular'),
			array('value'=>'Neucha','label' => 'Neucha'),
			array('value'=>'Neuton','label' => 'Neuton'),
			array('value'=>'News+Cycle','label' => 'News Cycle'),
			array('value'=>'Nixie+One','label' => 'Nixie One'),
			array('value'=>'Nobile','label' => 'Nobile'),
			array('value'=>'Nova+Cut','label' => 'Nova Cut'),
			array('value'=>'Nova+Flat','label' => 'Nova Flat'),
			array('value'=>'Nova+Mono','label' => 'Nova Mono'),
			array('value'=>'Nova+Oval','label' => 'Nova Oval'),
			array('value'=>'Nova+Round','label' => 'Nova Round'),
			array('value'=>'Nova+Script','label' => 'Nova Script'),
			array('value'=>'Nova+Slim','label' => 'Nova Slim'),
			array('value'=>'Nova+Square','label' => 'Nova Square'),
			array('value'=>'Nunito:light','label' => ' Nunito Light'),
			array('value'=>'Nunito','label' => ' Nunito Regular'),
			array('value'=>'Oswald','label' => 'Oswald'),
			array('value'=>'Reenie+Beanie','label' => 'Reenie Beanie'),
			array('value'=>'Pacifico','label' => 'Pacifico'),
			array('value'=>'Patrick+Hand','label' => 'Patrick Hand'),
			array('value'=>'Paytone+One','label' => 'Paytone One'),
			array('value'=>'Philosopher','label' => 'Philosopher'),
			array('value'=>'Play','label' => 'Play'),
			array('value'=>'Podkova','label' => ' Podkova '),
			array('value'=>'PT+Sans','label' => 'PT Sans'),
			array('value'=>'PT+Serif','label' => 'PT Serif'),
			array('value'=>'Puritan','label' => 'Puritan'),
			array('value'=>'Quattrocento','label' => 'Quattrocento'),
			array('value'=>'Radley','label' => 'Radley'),
			array('value'=>'Raleway:100','label' => 'Raleway'),
			array('value'=>'Redressed','label' => 'Redressed'),
			array('value'=>'Roboto+Condensed:300','label' => ' Roboto Condensed 300'),
			array('value'=>'Roboto+Condensed:400','label' => ' Roboto Condensed 400'),
			array('value'=>'Roboto+Condensed:700','label' => ' Roboto Condensed 700'),
			
			array('value'=>'Rock+Salt','label' => 'Rock Salt'),
			array('value'=>'Rokkitt','label' => 'Rokkitt'),
			array('value'=>'Schoolbell','label' => 'Schoolbell'),
			array('value'=>'Shanti','label' => 'Shanti'),
			array('value'=>'Sigmar+One','label' => 'Sigmar One'),
			array('value'=>'Six+Caps','label' => 'Six Caps'),
			array('value'=>'Slackey','label' => 'Slackey'),
			array('value'=>'Smythe','label' => 'Smythe'),
			array('value'=>'Sniglet:800','label' => 'Sniglet'),
			array('value'=>'Special+Elite','label' => 'Special Elite'),
			array('value'=>'Stardos+Stencil','label' => 'Stardos Stencil'),
			array('value'=>'Sunshiney','label' => 'Sunshiney'),
			array('value'=>'Syncopate','label' => 'Syncopate'),
			array('value'=>'Tangerine','label' => 'Tangerine'),
			array('value'=>'Tenor+Sans','label' => ' Tenor Sans '),
			array('value'=>'Tinos','label' => 'Tinos'),
			array('value'=>'Ubuntu','label' => 'Ubuntu'),
			array('value'=>'Ultra','label' => 'Ultra'),
			array('value'=>'Unkempt','label' => 'Unkempt'),
			array('value'=>'UnifrakturCook:bold','label' => 'UnifrakturCook'),
			array('value'=>'Varela','label' => 'Varela'),
			array('value'=>'Varela Round','label' => 'Varela Round'),
			array('value'=>'Vibur','label' => 'Vibur'),
			array('value'=>'Vollkorn','label' => 'Vollkorn'),
			array('value'=>'VT323','label' => 'VT323'),
			array('value'=>'Wallpoet','label' => 'Wallpoet'),
			array('value'=>'Wire+One','label' => 'Wire One'),
			array('value'=>'Yeseva+One','label' => 'Yeseva One'),
			array('value'=>'Zeyada','label' => 'Zeyada'),
			array('value'=>'Brandon','label' => 'Brandon'),
        );
    }

}
